apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: momice-dev-tls
spec:
  secretName: momice-dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: momice.dev
  dnsNames:
    - momice.dev
    - www.momice.dev
    - staging.momice.dev
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - momice.dev
          - www.momice.dev
          - staging.momice.dev
