apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: k8s-multi-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: momice.dev
  dnsNames:
    - momice.dev
    - www.momice.dev
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - momice.dev
          - www.momice.dev
